import {bindApproval,approvalValid,deliverySummary,governanceIssues,seedGovernance} from '../dist/governance.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {modules} from '../dist/modules.mjs';
import {newProject,reviewProject,createRelease,restoreRelease,validateWorkspace,cloneProject} from '../dist/store.mjs';
import {toCsv,fromCsv,createWorkbook,readWorkbook,mergeRows} from '../dist/spreadsheet.mjs';
import {captureTemplate,previewTemplate,applyTemplate} from '../dist/templates.mjs';
import {listSchemas} from '../dist/modules.mjs';
import {buildDocument} from '../dist/document.mjs';
import {mergeProjectSets} from '../dist/cloud.mjs';
import {createDefaultBep,createPilotBep,createPresetProject} from '../dist/presets.mjs';
import {issueTarget} from '../dist/issue-navigation.mjs';
import {lockKeyForView,sectionSnapshot,applySectionSnapshot} from '../dist/collaboration.mjs';

function completeProject(){
  const p=newProject({projectName:'Demo Hub',projectCode:'DHM',description:'A transport hub.',documentCode:'DHM-BEP-001',preparedBy:'BIM Manager',contractor:'MainCo',client:'ClientCo',consultant:'ConsultCo',cde:'ACC',crs:'EPSG:32638',verticalDatum:'MSL'});
  p.lists.references.push({title:'EIR',code:'EIR-001',revision:'01',status:'Adopted',source:'Client'});
  p.lists.software.push({use:'Authoring',product:'Revit',version:'2026',exchange:'RVT / IFC'});
  p.lists.models.push({code:'DHM-ARC-Z01',discipline:'Architecture',zone:'Zone 01',producer:'Architect'});
  p.lists.deliverables.push({title:'Coordinated model',producer:'MainCo',date:'2026-10-01',format:'NWD',acceptance:'No critical clashes'});
  p.lists.clashes.push({name:'MEP vs Structure',setA:'MEP',setB:'Structure',type:'Hard',tolerance:'0 mm',owner:'BIM Lead'});
  seedGovernance(p);
  p.fields.designResponsibility='Client design';p.fields.drawingStrategy='Discipline models';p.fields.loinSystem='Project matrix 01';
  p.lists.compliance=[{id:'REQ-1',source:'EIR-001 rev01 clause1',requirement:'Coordinate models',section:'coordination',owner:'BIM Lead',evidence:'QA-001',status:'Compliant'}];
  p.lists.mobilization.forEach(r=>Object.assign(r,{resources:'Assigned team of 3, licensed workstations',date:'2026-09-01',status:'Passed',evidence:'TEST-001',checker:'A. Checker'}));
  p.lists.risks=[];
  p.lists.deliverables.forEach(r=>Object.assign(r,{productionDays:'5',reviewDays:'2'}));
  p.lists.exchanges=[{exchange:'Model exchange',milestone:'Construction',sender:'Task team',receiver:'Coordinator',format:'NWC',status:'Planned'}];
  p.lists.loin=[{element:'Services',milestone:'Construction',geometry:'Coordinated routes',information:'System and sizes',documentation:'Shop drawings',responsible:'MEP team'}];
  approve(p);
  return p;
}
function approve(p){p.lists.approvals=['Technical review','Issue authorization'].map(stage=>({stage,revision:p.fields.revision,person:'A. Reviewer',role:'Designated authority',status:'Approved',date:'2026-09-07',evidence:'APP-001'}));p.lists.approvals.forEach((_,i)=>bindApproval(p,i));}

test('blank project reports critical gaps and cannot be ready',()=>{const p=newProject();const r=reviewProject(p);assert.equal(r.ready,false);assert.ok(r.critical>5);});
test('completed core project becomes ready while optional modules remain excluded',()=>{const p=completeProject(),r=reviewProject(p);assert.equal(r.ready,true);assert.equal(r.critical,0);});
test('COBie activates asset information and requires a declared version',()=>{const p=completeProject();p.moduleStates.cobie='required';let r=reviewProject(p);assert.ok(r.issues.some(i=>i.code==='dependency:cobie'));p.moduleStates.assets='required';assert.ok(reviewProject(p).issues.some(i=>i.code==='cobie'));p.fields.cobieVersion='2.4';p.lists.assetRequirements=[{asset:'AHU',property:'Asset ID',source:'Supplier',milestone:'Handover',format:'COBie',responsible:'MEP'}];assert.equal(reviewProject(p).critical,0);});
test('4D requires tool and programme source',()=>{const p=completeProject();p.moduleStates.fourD='optional';assert.ok(reviewProject(p).issues.some(i=>i.code==='fourD'));p.fields.fourDTool='Navisworks Manage 2026';p.fields.programmeSource='Approved baseline P6 Rev 03';assert.equal(reviewProject(p).critical,0);});
test('document numbers included modules contiguously and omits excluded content',()=>{const p=completeProject();p.moduleStates.fourD='optional';p.fields.fourDTool='Navisworks';p.fields.programmeSource='P6';const html=buildDocument(p,reviewProject(p));const active=modules.filter(m=>p.moduleStates[m.id]!=='not_applicable');active.forEach((m,i)=>{assert.ok(html.includes(`id="m-${m.id}"`));assert.ok(html.includes(`${i+1}. ${m.title.replaceAll('&','&amp;')}`));});assert.doesNotMatch(html,/5D &amp; quantity take-off/);});
test('user input is escaped in the generated BEP',()=>{const p=completeProject();p.fields.projectName='<img src=x onerror=alert(1)>';p.notes.overview='<script>alert(1)</script>';const html=buildDocument(p,reviewProject(p));assert.doesNotMatch(html,/<img|<script>/);assert.match(html,/&lt;img/);assert.match(html,/&lt;script/);});
test('frozen release restores without changing the frozen snapshot',()=>{const p=completeProject();approve(p);createRelease(p);const id=p.releases[0].id;p.fields.projectName='Changed';restoreRelease(p,id);assert.equal(p.fields.projectName,'Demo Hub');p.fields.projectName='Again';assert.equal(p.releases[0].snapshot.fields.projectName,'Demo Hub');});
test('duplicated project has a new identity and no release history',()=>{const p=completeProject();approve(p);createRelease(p);const copy=cloneProject(p);assert.notEqual(copy.id,p.id);assert.equal(copy.releases.length,0);assert.equal(copy.fields.projectCode,'');});
test('workspace validation rejects duplicate IDs and unsafe style data',()=>{const p=completeProject(),w={schemaVersion:2,activeProjectId:null,projects:[p]};assert.deepEqual(validateWorkspace(structuredClone(w)),w);assert.throws(()=>validateWorkspace({...w,projects:[p,p]}));const bad=structuredClone(w);bad.projects[0].style.accent='url(javascript:x)';assert.throws(()=>validateWorkspace(bad));});
test('cloud merge keeps the newest version of each project',()=>{const local=completeProject(),cloud=structuredClone(local);local.updatedAt='2026-09-05T12:00:00Z';cloud.updatedAt='2026-09-05T11:00:00Z';cloud.fields.projectName='Old cloud name';const remoteOnly=completeProject();remoteOnly.id='remote-only';const merged=mergeProjectSets([local],[cloud,remoteOnly]);assert.equal(merged.length,2);assert.equal(merged.find(p=>p.id===local.id).fields.projectName,'Demo Hub');assert.ok(merged.some(p=>p.id==='remote-only'));});
test('versioned cloud data wins over a newer-looking stale browser copy',()=>{const local=completeProject(),cloud=structuredClone(local);local.updatedAt='2026-09-06T12:00:00Z';local.dbVersion=2;local.fields.projectName='Stale local';cloud.updatedAt='2026-09-06T11:00:00Z';cloud.dbVersion=3;cloud.fields.projectName='Current cloud';const merged=mergeProjectSets([local],[cloud]);assert.equal(merged[0].fields.projectName,'Current cloud');assert.equal(merged[0].dbVersion,3);});
test('advanced schedules are rendered in their related BEP modules',()=>{const p=completeProject();p.lists.responsibilities.push({activity:'Model federation',responsible:'BIM Coordinator',accountable:'BIM Manager',consulted:'Task teams',informed:'Project Manager'});p.lists.exchanges.push({exchange:'Weekly model exchange',milestone:'Construction',sender:'Task teams',receiver:'Main contractor',format:'RVT / NWC',status:'Planned'});p.lists.loin.push({element:'Air handling unit',milestone:'Handover',geometry:'Installed geometry',information:'Asset properties',documentation:'O&M manual',responsible:'Mechanical contractor'});const html=buildDocument(p,reviewProject(p));assert.match(html,/Responsibility matrix/);assert.match(html,/Weekly model exchange/);assert.match(html,/Air handling unit/);});
test('legacy v2 projects gain new schedules and attachment fields during validation',()=>{const p=completeProject();delete p.lists.loin;delete p.lists.exchanges;delete p.attachments;delete p.style.logoPath;const validated=validateWorkspace({schemaVersion:2,activeProjectId:null,projects:[p]});assert.ok(Array.isArray(validated.projects[0].lists.loin));assert.ok(Array.isArray(validated.projects[0].attachments));assert.equal(validated.projects[0].style.logoPath,'');});
test('release snapshots preserve attachment metadata and clones do not reuse private files',()=>{const p=completeProject();p.attachments.push({id:'a1',path:'user/project/a1.pdf',name:'A1.pdf',size:100,type:'application/pdf',uploadedAt:'2026-09-05T12:00:00Z'});approve(p);createRelease(p);assert.equal(p.releases[0].snapshot.attachments[0].name,'A1.pdf');assert.equal(cloneProject(p).attachments.length,0);});
test('CSV schedules round-trip quoted content',()=>{const rows=[{title:'Model, drawing & report',producer:'Team "A"',date:'2026-09-05',format:'RVT\nPDF',acceptance:'Approved'}],csv=toCsv(rows,listSchemas.deliverables);assert.deepEqual(fromCsv(csv,listSchemas.deliverables).map(r=>Object.fromEntries(Object.keys(rows[0]).map(k=>[k,r[k]]))),rows);});
test('Excel workbook round-trips all recognized schedules',async()=>{const p=completeProject();p.lists.deliverables.push({title:'Federated model',producer:'BIM team',date:'2026-09-05',format:'NWD',acceptance:'Approved'});const parsed=await readWorkbook(createWorkbook(p.lists));assert.ok(parsed.tables.deliverables.some(row=>row.title==='Federated model'));assert.ok(Object.keys(parsed.tables).length>10);});
test('Excel worksheets place columns before sheet data as required by OpenXML',()=>{const source=fs.readFileSync(new URL('../dist/spreadsheet.mjs',import.meta.url),'utf8'),sheetBuilder=source.slice(source.indexOf('function sheetXml'),source.indexOf('export function createWorkbook'));assert.ok(sheetBuilder.indexOf('<cols>')<sheetBuilder.indexOf('<sheetData>'));});
test('document output does not include a skip-to-content control',()=>{const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');assert.doesNotMatch(html,/Skip to content/);});
test('printed section headers do not expose internal module status',()=>{const p=completeProject(),html=buildDocument(p,reviewProject(p));assert.doesNotMatch(html,/<div class="section-meta"><span>SECTION \d+<\/span><span>required<\/span>/);});
test('schedule merge skips exact duplicate rows',()=>{const rows=[{name:'A',role:'Client',code:'C',responsibility:'Approve'}],merged=mergeRows(rows,[...rows,{name:'B',role:'Lead',code:'L',responsibility:'Manage'}],listSchemas.parties);assert.equal(merged.length,2);});
test('client pack records source, previews conflicts and tracks application',()=>{const source=completeProject();source.fields.client='Client standard';source.lists.references.push({title:'EIR',code:'EIR-01',revision:'A',status:'Adopted',source:'Client'});const target=completeProject();target.fields.client='Existing client';const template=captureTemplate(source,'client',{name:'Client Pack',sourceReference:'EIR-01'}),preview=previewTemplate(target,template);assert.ok(preview.conflicts.some(x=>x.key==='client'));applyTemplate(target,template,'fill');assert.equal(target.fields.client,'Existing client');assert.equal(target.appliedTemplates[0].sourceReference,'EIR-01');assert.ok(target.templateConflicts.length);});
test('authentication page exposes all required account recovery controls',()=>{const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');for(const id of ['signin-form','signup-form','forgot-form','reset-form'])assert.match(html,new RegExp(`id="${id}"`));assert.ok((html.match(/name="confirmPassword"/g)||[]).length>=2);assert.ok((html.match(/data-toggle-password/g)||[]).length>=4);assert.match(html,/Remember my login/);assert.match(html,/Forgot password\?/);});
test('Turnstile protects sign in, sign up and password recovery',()=>{const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8'),cloud=fs.readFileSync(new URL('../dist/cloud.mjs',import.meta.url),'utf8'),headers=fs.readFileSync(new URL('../dist/_headers',import.meta.url),'utf8'),turnstile=fs.readFileSync(new URL('../dist/turnstile.mjs',import.meta.url),'utf8');for(const surface of ['signin','signup','forgot'])assert.match(html,new RegExp(`id="turnstile-${surface}"`));assert.match(turnstile,/0x4AAAAAAEp8c1SLjK-7NgDh/);assert.match(cloud,/gotrue_meta_security:\{captcha_token:captchaToken\}/);assert.match(headers,/script-src[^\n]+https:\/\/challenges\.cloudflare\.com/);assert.match(headers,/frame-src https:\/\/challenges\.cloudflare\.com/);});
test('built-in default and pilot BEPs are populated and carry source provenance',()=>{const baseline=createDefaultBep({projectName:'Live project',projectCode:'LP'}),pilot=createPilotBep();assert.equal(baseline.preset,'default');assert.equal(baseline.notes.overview.length>100,true);assert.ok(baseline.lists.references.length>=3);assert.equal(baseline.appliedTemplates[0].sourceReference.includes('QC00912017'),true);assert.equal(pilot.preset,'pilot');assert.equal(pilot.fields.projectName,'Northwest Transport Hub - Pilot');assert.equal(pilot.fields.contractor,'Pilot Main Contractor');assert.ok(pilot.lists.models.length>=3);assert.ok(buildDocument(pilot,reviewProject(pilot)).includes('PILOT / EXAMPLE - NOT FOR ISSUE'));});
test('legacy single logo migrates to ordered logo configuration and project copies clear private logos',()=>{const p=completeProject();p.style.logoPath='user/project/logo.png';delete p.style.logos;delete p.style.logoCount;const validated=validateWorkspace({schemaVersion:2,activeProjectId:p.id,projects:[p]}).projects[0];assert.equal(validated.style.logoCount,1);assert.equal(validated.style.logos[0].path,'user/project/logo.png');assert.equal(validated.style.logos[0].placement,'both');const copy=cloneProject(validated);assert.equal(copy.style.logoCount,0);assert.deepEqual(copy.style.logos,[]);});
test('review issue targets resolve exact views, fields and table rows',()=>{const p=completeProject();p.lists.decisions.push({status:'Open'});p.lists.appendices.push({status:'Missing'});assert.deepEqual(issueTarget('field:projectName',p),{view:'project',selector:'[data-field="projectName"]'});assert.equal(issueTarget('software',p).view,'information');assert.equal(issueTarget('module:overview',p).selector,'[data-module-card="overview"]');assert.equal(issueTarget('open-decisions',p).selector,'[data-list="decisions"][data-row="0"]');assert.equal(issueTarget('missing-appendices',p).selector,'[data-list="appendices"][data-row="0"]');});
test('preview pagination includes repeated page furniture and four configurable logo slots',()=>{const pagination=fs.readFileSync(new URL('../dist/pagination.mjs',import.meta.url),'utf8'),styles=fs.readFileSync(new URL('../dist/styles.css',import.meta.url),'utf8'),app=fs.readFileSync(new URL('../dist/app.mjs',import.meta.url),'utf8'),html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');assert.match(pagination,/class="page-header"/);assert.match(pagination,/class="page-footer"/);assert.match(pagination,/Page \$\{index\+1\} of \$\{total\}/);assert.match(styles,/\.doc-page\{width:210mm;height:297mm/);assert.match(app,/Choose up to four logos/);assert.match(app,/Cover \+ page header/);assert.match(html,/value="humain" checked/);assert.match(html,/value="pilot"/);});
test('cover page restores the branded background above the generic A4 page style',()=>{const styles=fs.readFileSync(new URL('../dist/styles.css',import.meta.url),'utf8');assert.match(styles,/\.doc-page\.cover-page\{background:linear-gradient/);assert.ok(styles.lastIndexOf('.doc-page.cover-page')>styles.indexOf('.doc-page{width:210mm;height:297mm'));});
test('sharing exposes public snapshots and one-use viewer or editor invitations',()=>{const app=fs.readFileSync(new URL('../dist/app.mjs',import.meta.url),'utf8'),cloud=fs.readFileSync(new URL('../dist/cloud.mjs',import.meta.url),'utf8'),html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');assert.match(html,/data-view="sharing"/);assert.match(app,/PUBLIC \/ READ ONLY/);assert.match(app,/Editor — can change the BEP/);assert.match(app,/Viewer — read and print only/);assert.match(cloud,/\?share=/);assert.match(cloud,/\?invite=/);assert.match(cloud,/get_bep_public_share/);assert.match(cloud,/accept_bep_project_invite/);assert.match(cloud,/crypto\.subtle\.digest\('SHA-256'/);assert.match(cloud,/stored\.attachments=\[\]/);});
test('shared projects preserve ownership and viewers cannot be uploaded',()=>{const p=completeProject();p.ownerId='owner-user';p.accessRole='viewer';const copy=cloneProject(p);assert.equal(copy.accessRole,'owner');assert.equal(copy.ownerId,'');const cloud=fs.readFileSync(new URL('../dist/cloud.mjs',import.meta.url),'utf8');assert.match(cloud,/project\.accessRole==='viewer'/);assert.match(cloud,/delete stored\.accessRole;delete stored\.ownerId/);assert.match(cloud,/method:'PATCH'/);});
test('collaboration schema uses RLS, hashed tokens and locked security-definer functions',()=>{const sql=fs.readFileSync(new URL('../supabase/schema.sql',import.meta.url),'utf8');for(const table of ['bep_project_collaborators','bep_project_invites','bep_public_shares'])assert.match(sql,new RegExp(`alter table public\\.${table} enable row level security`));assert.match(sql,/extensions\.digest\(p_token,'sha256'\)/);assert.match(sql,/security definer set search_path=''/);assert.match(sql,/revoke all on function public\.get_bep_public_share\(text\) from public/);assert.match(sql,/prevent_bep_project_owner_change/);assert.doesNotMatch(sql,/bep-public-previews/);});
test('public preview logos use expiring private-storage URLs allowed by CSP',()=>{const cloud=fs.readFileSync(new URL('../dist/cloud.mjs',import.meta.url),'utf8'),headers=fs.readFileSync(new URL('../dist/_headers',import.meta.url),'utf8');assert.match(cloud,/object\/sign\/bep-attachments/);assert.match(cloud,/expiresIn/);assert.match(headers,/img-src[^\n]+https:\/\/jtubxhixhiqeyxhpqgpf\.supabase\.co/);});
test('public preview hides editing navigation and uses the full document width',()=>{const css=fs.readFileSync(new URL('../dist/styles.css',import.meta.url),'utf8');assert.match(css,/\.public-preview \.sidebar,\.public-preview \.workarea\{display:none!important\}/);assert.match(css,/\.public-preview #editor\{display:grid!important;grid-template-columns:minmax\(0,1fr\)\}/);assert.match(css,/\.public-preview \.document-pane\{grid-column:1!important\}/);});
test('section snapshots isolate concurrent BEP work areas',()=>{const p=completeProject();p.fields.cde='ACC';p.lists.models.push({code:'M1'});const project=sectionSnapshot(p,'project'),technical=sectionSnapshot(p,'technical');assert.ok(project.fields.projectName);assert.equal(project.fields.cde,undefined);assert.ok(technical.fields.crs);assert.equal(technical.fields.projectName,undefined);assert.deepEqual(Object.keys(technical.lists),['models','namingFields','loin']);assert.equal(lockKeyForView('preview'),'');assert.equal(lockKeyForView('templates'),'__project__');});
test('section undo restores only the borrowed area',()=>{const p=completeProject(),before=sectionSnapshot(p,'project');p.fields.projectName='Changed';p.fields.cde='New CDE';applySectionSnapshot(p,'project',before);assert.equal(p.fields.projectName,'Demo Hub');assert.equal(p.fields.cde,'New CDE');});
test('collaboration UI exposes undo redo and section borrowing controls',()=>{const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8'),app=fs.readFileSync(new URL('../dist/app.mjs',import.meta.url),'utf8'),cloud=fs.readFileSync(new URL('../dist/cloud.mjs',import.meta.url),'utf8');assert.match(html,/id="undo"/);assert.match(html,/id="redo"/);assert.match(app,/Reserved to you/);assert.match(app,/Force release/);assert.match(app,/renewProjectSection/);assert.match(cloud,/acquire_bep_section_lock/);assert.match(cloud,/save_bep_project_section/);});
test('database borrowing is token-scoped, expiring and versioned',()=>{const sql=fs.readFileSync(new URL('../supabase/schema.sql',import.meta.url),'utf8');assert.match(sql,/add column version bigint not null default 1/);assert.match(sql,/bump_bep_project_version/);assert.match(sql,/create table public\.bep_section_locks/);assert.match(sql,/client_id uuid not null/);assert.match(sql,/interval '2 minutes'/);assert.match(sql,/pg_advisory_xact_lock/);assert.match(sql,/save_bep_project_section/);assert.match(sql,/p_expected_version<>v_project\.version/);assert.match(sql,/revoke all on function public\.acquire_bep_section_lock/);});

 test('HATCO and HUMAIN baselines survive backup, render procedures and preserve unresolved project inputs',()=>{for(const type of ['hatco','humain']){const p=createPresetProject(type);const w=validateWorkspace(JSON.parse(JSON.stringify({schemaVersion:2,activeProjectId:p.id,projects:[p]})));assert.equal(w.projects[0].preset,type);assert.equal(p.fields.contractor,'HATCO');assert.equal(Object.values(p.notes).filter(x=>x.length>100).length,29);assert.ok(p.lists.decisions.every(x=>x.status==='Open'));assert.equal(p.fields.crs,'');assert.equal(p.lists.models.length,0);assert.equal(p.moduleStates.cobie,'pending');const html=buildDocument(p,reviewProject(p));assert.match(html,/HAT-HVC-MECH_EQ-AHU/);assert.match(html,/HATCO working procedure/);assert.doesNotMatch(html,/<aside class="project-note">/);assert.ok(!reviewProject(p).ready);}const p=createPresetProject('humain');assert.equal(p.fields.projectName,'HUMAIN');assert.equal(p.lists.parties.find(x=>x.name==='JLL').role,'Owner representative');assert.equal(createPresetProject('hatco',{projectName:'Custom'}).fields.projectName,'Custom');});

test('company templates retain procedures and protect different project text in fill mode',()=>{const source=completeProject();source.notes.naming='Company naming procedure';const template=captureTemplate(source,'company',{name:'HATCO'});const target=newProject();applyTemplate(target,template);assert.equal(target.notes.naming,'Company naming procedure');target.notes.naming='Project exception';assert.ok(previewTemplate(target,template).conflicts.some(r=>r.area==='Procedure'));applyTemplate(target,template,'fill');assert.equal(target.notes.naming,'Project exception');applyTemplate(target,template,'overwrite');assert.equal(target.notes.naming,'Company naming procedure');});
test('legacy units normalize and all governance schedules migrate without losing records',()=>{const p=completeProject();p.fields.units='Length: mm; elevation: m; area: m²; volume: m³';delete p.lists.compliance;const q=validateWorkspace({schemaVersion:2,activeProjectId:p.id,projects:[p]}).projects[0];assert.equal(q.fields.units,'Millimetres');assert.deepEqual(q.lists.compliance,[]);assert.equal(q.lists.deliverables[0].title,'Coordinated model');});
test('placeholder and unsupported enum values block data completeness',()=>{const p=completeProject();p.fields.designResponsibility='Pending confirmation';p.fields.units='arbitrary units';const r=reviewProject(p);assert.equal(r.dataComplete,false);assert.ok(r.issues.some(i=>i.code==='field:designResponsibility'));assert.ok(r.issues.some(i=>i.code==='field:units'));});
test('approval cannot be reused after content changes and freeze checks the gate',()=>{const p=completeProject();assert.equal(reviewProject(p).ready,true);p.notes.authoring='Changed procedure';assert.equal(reviewProject(p).dataComplete,true);assert.equal(reviewProject(p).reviewed,false);assert.throws(()=>createRelease(p));approve(p);assert.equal(reviewProject(p).ready,true);p.lists.approvals[0].evidence='';assert.equal(reviewProject(p).reviewed,false);});
test('missing evidence, circular dependencies and unlinked package IDs are detected',()=>{const p=completeProject();const row=p.lists.deliverables[0];p.lists.deliverables.push({...row,id:'DEL-002',dependencies:row.id});row.dependencies='DEL-002';row.packageId='MISSING';p.lists.compliance[0].evidence='';const issues=governanceIssues(p);assert.ok(issues.some(r=>r.message.includes('Circular')));assert.ok(issues.some(r=>r.message.includes('package ID')));assert.ok(issues.some(r=>r.code==='row:compliance:0'));assert.equal(issueTarget('row:compliance:0',p).view,'information');});
test('delivery metrics distinguish issue dates from acceptance',()=>{const s=deliverySummary([{date:'2026-09-01',actualDate:'2026-09-01',status:'Submitted'},{date:'2026-09-01',actualDate:'2026-09-03',status:'Accepted',evidence:'ACC-1'},{date:'2026-09-01'}],'2026-09-07');assert.deepEqual(s,{total:3,issued:2,onTime:1,overdue:1,accepted:1});});
test('new schedules round-trip in workbook and stay inside their borrowed sections',async()=>{const p=completeProject();const x=await readWorkbook(createWorkbook(p.lists));assert.equal(x.tables.compliance[0].id,'REQ-1');assert.equal(x.tables.approvals[0].contentSnapshot,undefined);assert.equal(sectionSnapshot(p,'information').lists.compliance[0].id,'REQ-1');assert.ok(sectionSnapshot(p,'organization').lists.mobilization.length);assert.equal(sectionSnapshot(p,'technical').lists.compliance,undefined);const html=buildDocument(p,reviewProject(p));assert.match(html,/EIR compliance/);assert.match(html,/Mobilization and capability/);assert.match(html,/Production days/);});

test('future mobilization tests and managed risks allow BEP issue but keep production pending',()=>{const p=completeProject();p.lists.mobilization.forEach(r=>Object.assign(r,{status:'Planned',date:'2099-01-01',evidence:'',gate:'Before production'}));p.lists.risks=[{id:'R1',risk:'Supplier data delay',owner:'BIM lead',likelihood:'Medium',impact:'High',mitigation:'Track supplier data weekly with procurement',date:'2099-01-01',gate:'During execution',status:'Open',evidence:''}];approve(p);const r=reviewProject(p,'2026-09-07');assert.equal(r.dataComplete,true);assert.equal(r.ready,true);assert.equal(r.productionReady,false);assert.ok(r.executionIssues.some(x=>x.scope==='production'));assert.ok(r.executionIssues.some(x=>x.message.includes('high-impact')));assert.doesNotThrow(()=>createRelease(p));});
test('an explicit BEP issue condition remains blocking until its evidence is recorded',()=>{const p=completeProject();const row=p.lists.mobilization[0];Object.assign(row,{gate:'BEP issue',status:'Planned',evidence:''});approve(p);assert.equal(reviewProject(p).ready,false);Object.assign(row,{status:'Passed',evidence:'TEST-002'});assert.equal(reviewProject(p).dataComplete,true);assert.equal(reviewProject(p).reviewed,false);approve(p);assert.equal(reviewProject(p).ready,true);});
test('operational changes preserve plan approval and do not change the rendered BEP plan',()=>{const p=completeProject();const before=buildDocument(p,reviewProject(p));const score=reviewProject(p).score;Object.assign(p.lists.deliverables[0],{forecastDate:'2099-04-01',actualDate:'2099-04-02',revision:'C03',status:'Accepted',evidence:'TRANSMITTAL-NEW'});Object.assign(p.lists.mobilization[0],{status:'Failed',evidence:'Execution finding'});p.lists.exchanges[0].status='Submitted';assert.equal(reviewProject(p).reviewed,true);assert.equal(reviewProject(p).authorized,true);assert.equal(reviewProject(p).score,score);assert.equal(buildDocument(p,reviewProject(p)),before);assert.equal(reviewProject(p).productionReady,false);});
test('baseline, criteria and responsibility changes require renewed approval',()=>{for(const mutate of [p=>p.lists.deliverables[0].date='2099-01-01',p=>p.lists.mobilization[0].acceptance='A different required test',p=>p.lists.detailedResponsibilities[0].producer='Other team']){const p=completeProject();mutate(p);assert.equal(reviewProject(p).reviewed,false);assert.equal(reviewProject(p).authorized,false);}});
test('completeness is passed applicable plan checks divided by total; approvals and execution are excluded',()=>{const p=completeProject();p.fields.projectName='';p.lists.approvals=[];const r=reviewProject(p);assert.equal(r.score,Math.floor(100*r.completed/r.total));assert.equal(r.completed,r.checks.filter(c=>c.passed).length);assert.equal(r.total,r.checks.length);assert.ok(r.score<100);const q=completeProject();q.lists.approvals=[];q.lists.deliverables[0].actualDate='not-a-date';const s=reviewProject(q);assert.equal(s.score,100);assert.equal(s.ready,false);assert.ok(s.executionIssues.some(x=>x.message.includes('actualDate')));assert.equal(s.critical,0);});
test('conditional 4D requirements only enter the completeness denominator when enabled',()=>{const p=completeProject();const count=reviewProject(p).total;p.fields.fourDTool='';p.fields.programmeSource='';assert.equal(reviewProject(p).score,100);p.moduleStates.fourD='optional';const r=reviewProject(p);assert.equal(r.total,count+1);assert.ok(r.issues.some(x=>x.code==='fourD'));p.moduleStates.fourD='not_applicable';assert.equal(reviewProject(p).total,count);});
test('legacy whole-document approvals are preserved exactly and never silently re-scoped',()=>{const p=completeProject();const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;const snapshot=JSON.stringify(stable({fields:p.fields,lists:Object.fromEntries(Object.entries(p.lists).filter(([k])=>k!=='approvals')),notes:p.notes,moduleStates:p.moduleStates,style:p.style,attachments:p.attachments}));p.lists.approvals.forEach(row=>{delete row.approvalScope;row.contentSnapshot=snapshot;});assert.equal(reviewProject(p).reviewed,true);p.lists.deliverables[0].forecastDate='2099-01-01';assert.equal(reviewProject(p).reviewed,false);approve(p);assert.equal(p.lists.approvals[0].approvalScope,'bep-plan-v2');p.lists.deliverables[0].forecastDate='2099-02-01';assert.equal(reviewProject(p).reviewed,true);});

test('company standard release requires metadata and creates immutable version lineage',async()=>{
  const {draftStandard,releaseStandard,isReleasedStandard}=await import('../dist/standards.mjs');
  const source=createPresetProject('hatco'),draft=draftStandard(source,{name:'HATCO standard',sourceReference:'STD-01',version:'1.0'});
  assert.throws(()=>releaseStandard(draft),/required/);
  draft.data.standard.releaseNotes='Initial controlled baseline';
  const released=releaseStandard(draft);assert.ok(isReleasedStandard(released));assert.equal(draft.data.standard.status,'draft');
  const next=draftStandard(released);assert.notEqual(next.id,released.id);assert.equal(next.version,'');assert.equal(next.data.standard.parentId,released.id);
  next.data.fields.contractor='Revised contractor';assert.notEqual(released.data.fields.contractor,next.data.fields.contractor);
  next.version='1.0';next.data.standard.releaseNotes='Revision';assert.throws(()=>releaseStandard(next,[released]),/already exists/);
  next.version='1.1';assert.equal(releaseStandard(next,[released]).data.standard.familyId,released.data.standard.familyId);
  assert.throws(()=>releaseStandard(released),/new version/);
});

test('pinned standards survive section saves and releases; changing the pin requires new approval',async()=>{
  const {draftStandard,releaseStandard,standardLink}=await import('../dist/standards.mjs');
  const p=completeProject(),draft=draftStandard(createPresetProject('hatco'),{name:'HATCO standard',sourceReference:'STD-01',version:'1.0'});
  draft.data.standard.releaseNotes='Initial';const standard=releaseStandard(draft);
  p.standardLink=standardLink(standard,'fill');assert.equal(approvalValid(p,p.lists.approvals[0]),false);
  p.lists.approvals.forEach((_,i)=>bindApproval(p,i));createRelease(p);
  const old=structuredClone(p.standardLink),snapshot=sectionSnapshot(p,'__project__');assert.deepEqual(snapshot.standardLink,old);
  applySectionSnapshot(p,'coordination',sectionSnapshot(p,'coordination'));assert.deepEqual(p.standardLink,old);
  p.standardLink.version='1.1';assert.equal(approvalValid(p,p.lists.approvals[0]),false);
  restoreRelease(p,p.releases.at(-1).id);assert.deepEqual(p.standardLink,old);
  const html=buildDocument(p,reviewProject(p));assert.match(html,/Company standard baseline/);assert.match(html,/STD-01/);
  standard.data.fields.contractor='Later source change';assert.notEqual(p.fields.contractor,standard.data.fields.contractor);
});

test('restoring an older issue clears a later standard pin',()=>{
  const p=completeProject();createRelease(p);delete p.releases[0].snapshot.standardLink;
  p.standardLink={name:'Later standard',version:'2.0'};restoreRelease(p,p.releases[0].id);assert.equal(p.standardLink,null);
});

test('shared register suggestions deduplicate and leave imported values and other sections unchanged',async()=>{
  const {sharedOptions}=await import('../dist/standards.mjs');const p=newProject();
  p.lists.parties=[{name:'HATCO'},{name:'HATCO'}];p.lists.team=[{name:'Ahmed',role:'BIM Manager'}];
  p.lists.milestones=[{name:'Design gate'}];p.lists.detailedResponsibilities=[{id:'PKG-01'}];
  const before=structuredClone(p);
  assert.deepEqual(sharedOptions(p,'deliverables','producer'),['HATCO','Ahmed','BIM Manager']);
  assert.deepEqual(sharedOptions(p,'deliverables','milestone'),['Design gate']);
  assert.deepEqual(sharedOptions(p,'deliverables','packageId'),['PKG-01']);
  assert.deepEqual(sharedOptions(p,'team','organization'),['HATCO']);assert.deepEqual(p,before);
});

test('table filtering preserves original row indices and combines search terms with status',async()=>{
  const {matchingRows}=await import('../dist/table-tools.mjs');
  const rows=[{id:'D1',title:'MEP model',status:'Planned'},{id:'D2',title:'ARC model',status:'Submitted'},{id:'D3',title:'MEP drawing',status:'Submitted'}];
  assert.deepEqual(matchingRows(rows,'mep','Submitted'),[2]);assert.deepEqual(matchingRows(rows,'MODEL arc'),[1]);assert.deepEqual(matchingRows(rows,'missing'),[]);assert.deepEqual(matchingRows(rows),[0,1,2]);
});
test('bulk changes affect exactly the selected rows, reject stale data and protect identifiers',async()=>{
  const {previewBulk,applyBulk}=await import('../dist/table-tools.mjs');
  const rows=[{id:'D1',producer:'A'},{id:'D2',producer:'B'},{id:'D3',producer:'C'}],before=structuredClone(rows);
  const preview=previewBulk(rows,'deliverables',[0,2],'producer','HATCO'),updated=applyBulk(rows,preview);
  assert.deepEqual(rows,before);assert.equal(updated[1].producer,'B');assert.equal(updated[0].producer,'HATCO');assert.equal(updated[2].producer,'HATCO');assert.equal(preview.plan,true);
  rows[0].producer='A changed';assert.throws(()=>applyBulk(rows,preview),/schedule changed/);
  assert.throws(()=>previewBulk(rows,'deliverables',[0],'id','SAME'),/cannot/);
  assert.throws(()=>previewBulk(rows,'approvals',[0],'status','Approved'),/cannot/);
  assert.throws(()=>previewBulk(rows,'deliverables',[99],'producer','A'),/current rows/);
});
test('bulk validation rejects invalid dates, negative duration and unsupported enum values',async()=>{
  const {previewBulk}=await import('../dist/table-tools.mjs');const rows=[{}];
  assert.throws(()=>previewBulk(rows,'deliverables',[0],'date','2026-02-30'),/valid date/);
  assert.throws(()=>previewBulk(rows,'deliverables',[0],'productionDays','-1'),/non-negative/);
  assert.throws(()=>previewBulk(rows,'deliverables',[0],'status','Approved'),/listed value/);
  assert.equal(previewBulk(rows,'deliverables',[0],'date','').changes.length,0);
});
test('operational bulk changes preserve approval but mobilization exclusions and baseline dates are plan changes',async()=>{
  const {previewBulk,applyBulk}=await import('../dist/table-tools.mjs');const p=completeProject();
  const preview=previewBulk(p.lists.deliverables,'deliverables',[0],'forecastDate','2099-01-01');assert.equal(preview.plan,false);
  p.lists.deliverables=applyBulk(p.lists.deliverables,preview);assert.equal(approvalValid(p,p.lists.approvals[0]),true);
  assert.equal(previewBulk(p.lists.deliverables,'deliverables',[0],'date','2099-01-01').plan,true);
  const mobilization=[{status:'Planned',gate:'Before production'}];
  assert.equal(previewBulk(mobilization,'mobilization',[0],'status','Passed').plan,false);
  assert.equal(previewBulk(mobilization,'mobilization',[0],'status','Not applicable').plan,true);
  assert.equal(previewBulk([{status:'Planned',gate:'BEP issue'}],'mobilization',[0],'status','Passed').plan,true);
});
test('opening a controlled change invalidates approval and whole-project undo restores the recorded baseline',async()=>{
  const {baselineToken,hasControlledBaseline}=await import('../dist/table-tools.mjs');const p=completeProject(),token=baselineToken(p),snapshot=sectionSnapshot(p,'__project__');
  assert.equal(hasControlledBaseline(p),true);assert.equal(hasControlledBaseline(newProject()),false);
  p.lists.changeLog.push({revision:p.fields.revision,date:'2026-09-07',sections:'Delivery',reason:'Controlled change opened: revised milestones',reference:'RFI-001',author:'BIM lead'});
  assert.equal(approvalValid(p,p.lists.approvals[0]),false);assert.equal(baselineToken(p),token);
  applySectionSnapshot(p,'__project__',snapshot);assert.equal(approvalValid(p,p.lists.approvals[0]),true);
});
test('bulk section snapshot can be undone without reverting another section',async()=>{
  const {previewBulk,applyBulk}=await import('../dist/table-tools.mjs');const p=completeProject(),before=sectionSnapshot(p,'coordination');
  p.lists.deliverables=applyBulk(p.lists.deliverables,previewBulk(p.lists.deliverables,'deliverables',[0],'producer','Changed team'));
  p.lists.parties.push({name:'Independent organization update'});applySectionSnapshot(p,'coordination',before);
  assert.notEqual(p.lists.deliverables[0].producer,'Changed team');assert.equal(p.lists.parties.at(-1).name,'Independent organization update');
});
