import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {modules} from '../dist/modules.mjs';
import {newProject,reviewProject,createRelease,restoreRelease,validateWorkspace,cloneProject} from '../dist/store.mjs';
import {toCsv,fromCsv,createWorkbook,readWorkbook,mergeRows} from '../dist/spreadsheet.mjs';
import {captureTemplate,previewTemplate,applyTemplate} from '../dist/templates.mjs';
import {listSchemas} from '../dist/modules.mjs';
import {buildDocument} from '../dist/document.mjs';
import {mergeProjectSets} from '../dist/cloud.mjs';

function completeProject(){
  const p=newProject({projectName:'Demo Hub',projectCode:'DHM',description:'A transport hub.',documentCode:'DHM-BEP-001',preparedBy:'BIM Manager',contractor:'MainCo',client:'ClientCo',consultant:'ConsultCo',cde:'ACC',crs:'EPSG:32638',verticalDatum:'MSL'});
  p.lists.references.push({title:'EIR',code:'EIR-001',revision:'01',status:'Adopted',source:'Client'});
  p.lists.software.push({use:'Authoring',product:'Revit',version:'2026',exchange:'RVT / IFC'});
  p.lists.models.push({code:'DHM-ARC-Z01',discipline:'Architecture',zone:'Zone 01',producer:'Architect'});
  p.lists.deliverables.push({title:'Coordinated model',producer:'MainCo',date:'2026-10-01',format:'NWD',acceptance:'No critical clashes'});
  p.lists.clashes.push({name:'MEP vs Structure',setA:'MEP',setB:'Structure',type:'Hard',tolerance:'0 mm',owner:'BIM Lead'});
  return p;
}

test('blank project reports critical gaps and cannot be ready',()=>{const p=newProject();const r=reviewProject(p);assert.equal(r.ready,false);assert.ok(r.critical>5);});
test('completed core project becomes ready while optional modules remain excluded',()=>{const p=completeProject(),r=reviewProject(p);assert.equal(r.ready,true);assert.equal(r.critical,0);});
test('COBie activates asset information and requires a declared version',()=>{const p=completeProject();p.moduleStates.cobie='required';let r=reviewProject(p);assert.ok(r.issues.some(i=>i.code==='dependency:cobie'));p.moduleStates.assets='required';assert.ok(reviewProject(p).issues.some(i=>i.code==='cobie'));p.fields.cobieVersion='2.4';assert.equal(reviewProject(p).critical,0);});
test('4D requires tool and programme source',()=>{const p=completeProject();p.moduleStates.fourD='optional';assert.ok(reviewProject(p).issues.some(i=>i.code==='fourD'));p.fields.fourDTool='Navisworks Manage 2026';p.fields.programmeSource='Approved baseline P6 Rev 03';assert.equal(reviewProject(p).critical,0);});
test('document numbers included modules contiguously and omits excluded content',()=>{const p=completeProject();p.moduleStates.fourD='optional';p.fields.fourDTool='Navisworks';p.fields.programmeSource='P6';const html=buildDocument(p,reviewProject(p));const active=modules.filter(m=>p.moduleStates[m.id]!=='not_applicable');active.forEach((m,i)=>{assert.ok(html.includes(`id="m-${m.id}"`));assert.ok(html.includes(`${i+1}. ${m.title.replaceAll('&','&amp;')}`));});assert.doesNotMatch(html,/5D &amp; quantity take-off/);});
test('user input is escaped in the generated BEP',()=>{const p=completeProject();p.fields.projectName='<img src=x onerror=alert(1)>';p.notes.overview='<script>alert(1)</script>';const html=buildDocument(p,reviewProject(p));assert.doesNotMatch(html,/<img|<script>/);assert.match(html,/&lt;img/);assert.match(html,/&lt;script/);});
test('frozen release restores without changing the frozen snapshot',()=>{const p=completeProject();createRelease(p);const id=p.releases[0].id;p.fields.projectName='Changed';restoreRelease(p,id);assert.equal(p.fields.projectName,'Demo Hub');p.fields.projectName='Again';assert.equal(p.releases[0].snapshot.fields.projectName,'Demo Hub');});
test('duplicated project has a new identity and no release history',()=>{const p=completeProject();createRelease(p);const copy=cloneProject(p);assert.notEqual(copy.id,p.id);assert.equal(copy.releases.length,0);assert.equal(copy.fields.projectCode,'');});
test('workspace validation rejects duplicate IDs and unsafe style data',()=>{const p=completeProject(),w={schemaVersion:2,activeProjectId:null,projects:[p]};assert.deepEqual(validateWorkspace(structuredClone(w)),w);assert.throws(()=>validateWorkspace({...w,projects:[p,p]}));const bad=structuredClone(w);bad.projects[0].style.accent='url(javascript:x)';assert.throws(()=>validateWorkspace(bad));});
test('cloud merge keeps the newest version of each project',()=>{const local=completeProject(),cloud=structuredClone(local);local.updatedAt='2026-09-05T12:00:00Z';cloud.updatedAt='2026-09-05T11:00:00Z';cloud.fields.projectName='Old cloud name';const remoteOnly=completeProject();remoteOnly.id='remote-only';const merged=mergeProjectSets([local],[cloud,remoteOnly]);assert.equal(merged.length,2);assert.equal(merged.find(p=>p.id===local.id).fields.projectName,'Demo Hub');assert.ok(merged.some(p=>p.id==='remote-only'));});
test('advanced schedules are rendered in their related BEP modules',()=>{const p=completeProject();p.lists.responsibilities.push({activity:'Model federation',responsible:'BIM Coordinator',accountable:'BIM Manager',consulted:'Task teams',informed:'Project Manager'});p.lists.exchanges.push({exchange:'Weekly model exchange',milestone:'Construction',sender:'Task teams',receiver:'Main contractor',format:'RVT / NWC',status:'Planned'});p.lists.loin.push({element:'Air handling unit',milestone:'Handover',geometry:'Installed geometry',information:'Asset properties',documentation:'O&M manual',responsible:'Mechanical contractor'});const html=buildDocument(p,reviewProject(p));assert.match(html,/Responsibility matrix/);assert.match(html,/Weekly model exchange/);assert.match(html,/Air handling unit/);});
test('legacy v2 projects gain new schedules and attachment fields during validation',()=>{const p=completeProject();delete p.lists.loin;delete p.lists.exchanges;delete p.attachments;delete p.style.logoPath;const validated=validateWorkspace({schemaVersion:2,activeProjectId:null,projects:[p]});assert.ok(Array.isArray(validated.projects[0].lists.loin));assert.ok(Array.isArray(validated.projects[0].attachments));assert.equal(validated.projects[0].style.logoPath,'');});
test('release snapshots preserve attachment metadata and clones do not reuse private files',()=>{const p=completeProject();p.attachments.push({id:'a1',path:'user/project/a1.pdf',name:'A1.pdf',size:100,type:'application/pdf',uploadedAt:'2026-09-05T12:00:00Z'});createRelease(p);assert.equal(p.releases[0].snapshot.attachments[0].name,'A1.pdf');assert.equal(cloneProject(p).attachments.length,0);});
test('CSV schedules round-trip quoted content',()=>{const rows=[{title:'Model, drawing & report',producer:'Team "A"',date:'2026-09-05',format:'RVT\nPDF',acceptance:'Approved'}],csv=toCsv(rows,listSchemas.deliverables);assert.deepEqual(fromCsv(csv,listSchemas.deliverables),rows);});
test('Excel workbook round-trips all recognized schedules',async()=>{const p=completeProject();p.lists.deliverables.push({title:'Federated model',producer:'BIM team',date:'2026-09-05',format:'NWD',acceptance:'Approved'});const parsed=await readWorkbook(createWorkbook(p.lists));assert.ok(parsed.tables.deliverables.some(row=>row.title==='Federated model'));assert.ok(Object.keys(parsed.tables).length>10);});
test('schedule merge skips exact duplicate rows',()=>{const rows=[{name:'A',role:'Client',code:'C',responsibility:'Approve'}],merged=mergeRows(rows,[...rows,{name:'B',role:'Lead',code:'L',responsibility:'Manage'}],listSchemas.parties);assert.equal(merged.length,2);});
test('client pack records source, previews conflicts and tracks application',()=>{const source=completeProject();source.fields.client='Client standard';source.lists.references.push({title:'EIR',code:'EIR-01',revision:'A',status:'Adopted',source:'Client'});const target=completeProject();target.fields.client='Existing client';const template=captureTemplate(source,'client',{name:'Client Pack',sourceReference:'EIR-01'}),preview=previewTemplate(target,template);assert.ok(preview.conflicts.some(x=>x.key==='client'));applyTemplate(target,template,'fill');assert.equal(target.fields.client,'Existing client');assert.equal(target.appliedTemplates[0].sourceReference,'EIR-01');assert.ok(target.templateConflicts.length);});
test('authentication page exposes all required account recovery controls',()=>{const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');for(const id of ['signin-form','signup-form','forgot-form','reset-form'])assert.match(html,new RegExp(`id="${id}"`));assert.ok((html.match(/name="confirmPassword"/g)||[]).length>=2);assert.ok((html.match(/data-toggle-password/g)||[]).length>=4);assert.match(html,/Remember my login/);assert.match(html,/Forgot password\?/);});
